# values.yaml
userService:
  name: "user-service"
  replicas: 2
  image: "nayer564/meeting-room-reservation-user-service"
  tag: "latest"
  port: 8001

salleService:
  name: "salle-service"
  replicas: 2
  image: "nayer564/meeting-room-reservation-salle-service"
  tag: "latest"
  port: 8002

reservationService:
  name: "reservation-service"
  replicas: 2
  image: "nayer564/meeting-room-reservation-reservation-service"
  tag: "latest"
  port: 8003

apiGateway:
  name: "api-gateway"
  replicas: 2
  image: "nayer564/meeting-room-reservation-api-gateway"
  tag: "latest"
  port: 8080

frontend:
  name: "frontend"
  replicas: 2
  image: "nayer564/meeting-room-reservation-frontend"
  tag: "latest"
  port: 3000

postgres:
  name: "postgres"
  replicas: 1
  image: "postgres"
  tag: "latest"
  port: 5432

zookeeper:
  name: "zookeeper"
  replicas: 1
  image: "confluentinc/cp-zookeeper"
  tag: "latest"
  port: 2181

kafka:
  name: "kafka"
  replicas: 1
  image: "confluentinc/cp-kafka"
  tag: "latest"
  port: 9092

ingress:
  name: "meeting-room-ingress"

secrets:
  name: "app-secrets"