services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    env_file:
      - ./user-service/.env
    environment:
      - DATABASE_URL=postgresql://meeting_user:12345@postgres:5432/meeting_room_db
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_SECRET=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped
    command: ["sh", "-c", "sleep 40 && uvicorn main:app --host 0.0.0.0 --port 8001"]
    networks:
      - app-network

  salle-service:
    build: ./salle-service
    ports:
      - "8002:8002"
    env_file:
      - ./salle-service/.env
    environment:
      - DATABASE_URL=postgresql://meeting_user:12345@postgres:5432/meeting_room_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_SECRET=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped
    command: ["sh", "-c", "sleep 60 && uvicorn main:app --host 0.0.0.0 --port 8002"]
    networks:
      - app-network

  reservation-service:
    build: ./reservation-service
    ports:
      - "8003:8003"
    env_file:
      - ./reservation-service/.env
    environment:
      - DATABASE_URL=postgresql://meeting_user:12345@postgres:5432/meeting_room_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_SECRET=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      salle-service:
        condition: service_started  
    restart: unless-stopped
    command: ["sh", "-c", "sleep 40 && uvicorn main:app --host 0.0.0.0 --port 8003"]
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=meeting_room_db
      - POSTGRES_USER=meeting_user
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meeting_user -d meeting_room_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    healthcheck:
      test: ["CMD", "/opt/bitnami/zookeeper/bin/zkServer.sh", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      app-network:
        aliases:
          - zookeeper

  kafka:
    image: bitnami/kafka:3.7
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      app-network:
        aliases:
          - kafka

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  zookeeper_data:
  kafka_data: