global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'meeting-room-services'
    static_configs:
      - targets: ['user-service:8001', 'salle-service:8002', 'reservation-service:8003', 'api-gateway:8080', 'frontend:80']
        labels:
          group: 'services'
