# Deployment for user-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.userService.name }}
spec:
  replicas: {{ .Values.userService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.userService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.userService.name }}
    spec:
      containers:
      - name: {{ .Values.userService.name }}
        image: {{ .Values.userService.image }}:{{ .Values.userService.tag }}
        ports:
        - containerPort: {{ .Values.userService.port }}
        env:
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: GOOGLE_CLIENT_SECRET
---
# Deployment for salle-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.salleService.name }}
spec:
  replicas: {{ .Values.salleService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.salleService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.salleService.name }}
    spec:
      containers:
      - name: {{ .Values.salleService.name }}
        image: {{ .Values.salleService.image }}:{{ .Values.salleService.tag }}
        ports:
        - containerPort: {{ .Values.salleService.port }}
---
# Deployment for reservation-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.reservationService.name }}
spec:
  replicas: {{ .Values.reservationService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.reservationService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.reservationService.name }}
    spec:
      containers:
      - name: {{ .Values.reservationService.name }}
        image: {{ .Values.reservationService.image }}:{{ .Values.reservationService.tag }}
        ports:
        - containerPort: {{ .Values.reservationService.port }}
---
# Deployment for api-gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiGateway.name }}
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiGateway.name }}
    spec:
      containers:
      - name: {{ .Values.apiGateway.name }}
        image: {{ .Values.apiGateway.image }}:{{ .Values.apiGateway.tag }}
        ports:
        - containerPort: {{ .Values.apiGateway.port }}
---
# Deployment for frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
      - name: {{ .Values.frontend.name }}
        image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
---
# Deployment for postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.postgres.name }}
        image: {{ .Values.postgres.image }}:{{ .Values.postgres.tag }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
---
# Deployment for zookeeper
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.zookeeper.name }}
spec:
  replicas: {{ .Values.zookeeper.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.zookeeper.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.zookeeper.name }}
    spec:
      containers:
      - name: {{ .Values.zookeeper.name }}
        image: {{ .Values.zookeeper.image }}:{{ .Values.zookeeper.tag }}
        ports:
        - containerPort: {{ .Values.zookeeper.port }}
---
# Deployment for kafka
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name }}
    spec:
      containers:
      - name: {{ .Values.kafka.name }}
        image: {{ .Values.kafka.image }}:{{ .Values.kafka.tag }}
        ports:
        - containerPort: {{ .Values.kafka.port }}